# Generated by Django 6.0.1 on 2026-02-11 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_asistencia_options_clase_cuestionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='academico.clase'),
        ),
    ]
