# Generated by Django 6.0.1 on 2026-02-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_cuestionario_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nombre',
        ),
        migrations.AddField(
            model_name='nota',
            name='cuestionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.cuestionario'),
        ),
    ]
