# Generated by Django 6.0.1 on 2026-02-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_remove_nota_nombre_nota_cuestionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='permite_multiple',
        ),
    ]
